language: python
python:
  - "2.7"
install:
  - pip install numpy
  - pip install .
script:
  - nosetests
services:
  - redis-server
before_script:
  # For PostgreSQL, from http://docs.travis-ci.com/user/database-setup/#PostgreSQL
  - psql -c 'create database qiita_test;' -U postgres
  - psql -d qiita_test -U postgres -f qiita_db/setup/qiita-db.sql
  - psql -d qiita_test -U postgres -f qiita_db/setup/initialize.sql
