language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install .
script:
  - qiita_db make_test_env
  - nosetests --with-doctest
  # we need to run the test suite from setup.py for coveralls to grab the info
  - coverage run setup.py test
  - coverage report -m
services:
  - redis-server
after_success:
  - coveralls
